export const BASE_URL = 'http://localhost:8080';

export const STORAGE_USER = 'user';

export const AUTHORIZATION_HEADER = 'Authorization';
export const AUTHORIZATION_VALUE = 'AUTHORIZATION_VALUE';


export const SERVER_MESSAGE_TYPE_GAME_UPDATE = 'GAME_UPDATE';
export const SERVER_MESSAGE_TYPE_GAME_START = 'GAME_START';
export const SERVER_MESSAGE_TYPE_ERROR = 'ERROR';
export const SERVER_MESSAGE_TYPE_SHORT_MESSAGE = 'SHORT_MESSAGE';


export const CLIENT_MESSAGE_TYPE_TAKE_COIN_FROM_DECK = 'TAKE_COIN_FROM_DECK';
export const CLIENT_MESSAGE_TYPE_DRAW_CARD_FROM_DECK = 'DRAW_CARD_FROM_DECK';
export const CLIENT_MESSAGE_TYPE_ASK_FOR_ACTIVE_GAME_UPDATE = 'ASK_FOR_ACTIVE_GAME_UPDATE';
export const CLIENT_MESSAGE_TYPE_SELL_SHIP = 'SELL_SHIP';
export const CLIENT_MESSAGE_TYPE_DESTROY_SHIP = 'DESTROY_SHIP';
export const CLIENT_MESSAGE_TYPE_BUY_PERSON = 'BUY_PERSON';
export const CLIENT_MESSAGE_TYPE_PASS = 'PASS';
